name: Get Corssword

on:
  push:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 */24 * * *'

jobs:
  Fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get Last Puzzle
      run: |
        lastPuzzle=$(cat num)

    - name: Curl Pdf
      run: |
        echo $lastPuzzle
