name: Get Crossword

on:
  push:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 */24 * * *'

jobs:
  Fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Curl Pdf
      env:
        TOKEN: ${{ secrets.session }}
      run: |
        lastPuzzle=$(cat num)
        curl --location --request GET 'https://www.nytimes.com/svc/crosswords/v2/puzzle/17888.pdf' \
        --header 'authority: nyt-games-prd.appspot.com' \
        --header 'accept: application/json, text/plain, */*' \
        --header 'nyt-s: 1EImRQBepkJ29q2KATfsFdnmBF/G1tddrChBQMi/UivYNnkeD59mNAKe4AJYOLZ43LjOoea6bgYnQKF/qeT2al4Z7tCfMJG9Ni1nwV9WxD8SLIovCoPansQD8Aa6xs01rZe6vvj8cyDo40' \
        --header 'sec-fetch-dest: empty' \
        --header 'origin: https://www.nytimes.com' \
        --header 'sec-fetch-site: cross-site' \
        --header 'sec-fetch-mode: cors' \
        --header 'referer: https://www.nytimes.com/crosswords/game/daily/2020/03/06' \
        --header 'accept-language: en-US,en;q=0.9' \
        -o $lastPuzzle.pdf
        cat $lastPuzzle.pdf
        
#     - name: "Configure git"
#       run: |
#         # Tell git who we are.
#         git config --global user.name "github-actions"
#         git config --global user.email "github-actions@users.noreply.github.com"
        
#     - name: "Add, commit and push changes"
#       run: |
#         git add .
#         lastPuzzle=$(cat num)
#         echo $lastPuzzle
#         git commit -m "saving $lastPuzzle to repo"
    
#     - name: GitHub Push
#       uses: ad-m/github-push-action@v0.5.0
#       with:
#         # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
#         github_token: ${{ secrets.GITHUB_TOKEN }}
        
